### ISSUE TITLE
There is an error when test the sample video?

### ISSUE THREAD

**Issue by lovechang1986** [nabang1010/YOLOv8_Object_Tracking_TensorRT#1]
Hi, I have test the install on jetson orin nano, but when I try the sample video, error below:

File "yolov8_deepsort_trt.py", line 105 in main
 frame = draw_roi(frame)
Name Error: name 'draw_roi' is not defined??

Thanks your wanderful repo.

**Comment by nabang1010** [comment]
oh, this is one function to draw all roi using to count object (i have removed it). You can comment this line and it can run normally

`# frame = draw_roi(frame)`

**Comment by lovechang1986** [comment]
Thanks, It works for me.
