### ISSUE TITLE
Vidio write error?

### ISSUE THREAD

**Issue by lovechang1986** [nabang1010/YOLOv8_Object_Tracking_TensorRT#3]
Hi ,  I check the `output_ds.avi` video. There must be something error occured.
The frame in video not has recognize and tracker areas and frame not change from start to end of the video?

Any way, the output video is so big.. ~9GB. My source video is 1.2GB.

**Comment by nabang1010** [comment]
What is your video resolution (width, height) and fps ?

I have fixed the fps of output video in `line 62` in `yolov8_deepsort_trt.py`

```python
out = cv2.VideoWriter('output_ds.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 30, (video_width,video_height))
```

Try change this fps values.

**Comment by lovechang1986** [comment]
My video's fps is 30 and 1980*1080.

**Comment by nabang1010** [comment]
When you add `--show` flag, can you see result (detected box and object id) ?

**Comment by lovechang1986** [comment]
show is allways right.

**Comment by lovechang1986** [comment]
I'm not build opencv. 
I tested reading and writing video directly opencv and found the same thing. It's possible that it's a problem with opencv.

**Comment by nabang1010** [comment]
Maybe it caused by large file, let try with smaller before build OpenCV

**Comment by nabang1010** [comment]
What tool do you use to play this output video?

**Comment by lovechang1986** [comment]
Ubuntu's own player. I'll open the original video in this player tomorrow and see how it goes.

**Comment by nabang1010** [comment]
I think you need to try open output video with VLC

**Comment by lovechang1986** [comment]
use the 'mp4v' it's ok. Don't know what happend...
