### ISSUE TITLE
Question : Using bytetrack or deepsort, which one is faster?

### ISSUE THREAD

**Issue by PluszZh** [nabang1010/YOLOv8_Object_Tracking_TensorRT#5]

**Comment by nabang1010** [comment]
BYTETrack faster than DeepSORT. DeepSORT have  an AI model for object feature appearance extraction, and it will make DeepSORT slower thane BYTETtrack

**Comment by PluszZh** [comment]
Thanks! But I use ByteTrack on a Jetson NX and obtained an FPS of around 24, which is lower than your result .....

**Comment by nabang1010** [comment]
> Thanks! But I use ByteTrack on a Jetson NX and obtained an FPS of around 24, which is lower than your result .....

What is your YOLO verion and model type you are using ?. But in my Repo, i don't give infomation about FPS with BYTETrack on Jetson NX, why you know your result lower than me ?
